In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df= pd.read_csv("play_tennis.csv")
df.head

<bound method NDFrame.head of     day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No>

In [6]:
df.shape

(14, 6)

In [7]:


df.drop(columns=['day'], inplace=True)
df.head

<bound method NDFrame.head of      outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No>

In [8]:
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [9]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
py=9/14
pn=5/14

In [11]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [12]:
#outlook
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
pon=0
prn=2/5
psn=3/5

poy=1
pry=3/5
psy=2/5

In [14]:
#temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
pcn=1/4
phn=2/4
pmn=2/6

pcy=3/4
phy=2/4
pmy=4/6

In [16]:
#humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
phn=4/7
pnn=1/7

phy=3/7
pny=6/7

In [18]:
#wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
psn=3/6
pwn=2/8

psy=3/6
pwy=6/8

In [20]:
#outlook=sunny, temp=hot, humidity=high, wind=weak
pyes=psy*phy*phy*py*pwn
print(pyes)

0.014759475218658892

In [21]:
pno=psn*phn*phn*pn*pwy
print(pno)

0.043731778425655975

<h1>Naive Bayes</h1>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df= pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [19]:
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [20]:
df= df.sample(10000)
df.shape

(10000, 2)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 10287 to 5329
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  object
dtypes: object(2)
memory usage: 234.4+ KB

In [22]:
df['sentiment'] = df['sentiment'].replace({
    'positive': 1,
    'negative': 0
})
df

C:\Users\vroy4\AppData\Local\Temp\ipykernel_14568\2959924288.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sentiment'] = df['sentiment'].replace({

                                                  review  sentiment
10287  I saw this movie at a screener and its the bes...          1
13294  Every motion picture Bette Davis stars in is w...          1
30699  This movie was God-awful, from conception to e...          0
26905  I dislike this movie a lot. If you've read the...          0
16662  Professor Paul Steiner is doing research in ma...          0
...                                                  ...        ...
42467  Beware the Scottish Play! In his riveting and ...          1
4981   I was mighty impressed with Nurse Betty all th...          1
22458  Rachel, Jo, Hannah, Tina, Bradley and John are...          0
45665  Did someone find the plot somewhere in the fil...          0
5329   This movie was just plain bad. Just about ever...          0

[10000 rows x 2 columns]

In [23]:
import re
clean= re.compile('<,*?>')
re.sub(clean,'',df.iloc[2].review)

'This movie was God-awful, from conception to execution. The US needs to set up a "Star Wars" site in this remote country? This is their premise? The way to gain access, the US concludes, is to win an obstacle course like cross-country race, where the winner can ask anything of the leader. And who better to win this race known as the "Game" than a gymnast? Of course! A gymnast would be the perfect choice for this mission. And don\'t forget that his father was an operative. Lucky for our hero, there happen to be gymnastic equipment in fortunate spots, like the stone pommel horse in the middle of a square (for no reason) amidst crazy town. Perfect.<br /><br />But above and beyond the horrible, HORIBBLE premise, is the awkward fumblings of the romantic scenes, the obviously highly depressed ninjas whose only job seems to be holding a flag to point out the race path, and the worst climax ever. After winning the race, our hero puts forth the wishes of the US government. And lo and behold, all the effort was worth it, because the US gets its "Star Wars" site! Huzzah! THIS IS YOUR TRIUMPHANT ENDING?! Wow.<br /><br />But still, being such a bad movie, it can be great fun to watch. The cover alone, depicting ninjas with machine guns, was enough to get me to rent this film.<br /><br />But if I were ever to meet Kurt Thomas (the gymnast-star) in real life, I would probably kick him in the face after a double somersault with 2 1/2 twists in the layout position.'

In [24]:
def clean_html(text):
    clean=re.compile('<,*?>')
    return re.sub(clean,'',text)

In [25]:
df['review']=df['review'].apply(clean_html)
print("done")

done

In [26]:
def lower_case(text):
    return text.lower()

In [27]:
df['review']=df['review'].apply(lower_case)
print("done")

done

In [28]:
def removal_spl(text):
    x= ''
    for i in text:
        if i.isalnum():
            x=x+i
        else:
            x=x+''
    return x

In [29]:
df['review']=df['review'].apply(removal_spl)
print("done")

done

In [30]:
x.shape

NameError: name 'x' is not defined

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stop_words = set(stopwords.words('english'))
ps = PorterStemmer()

def preprocess(text):

    # safety check (important for consecutive runs)
    if not isinstance(text, str):
        text = " ".join(text)

    # lowercase
    words = text.lower().split()

    # remove stopwords
    words = [w for w in words if w not in stop_words]

    # stemming
    words = [ps.stem(w) for w in words]

    # join back
    return " ".join(words)


df['review'] = df['review'].apply(preprocess)

print("Preprocessing Done ")

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [ ]:
x=cv.fit_transform(df['review']).toarray()

In [ ]:
x.shape

In [ ]:
df

In [31]:
x[0].max()

NameError: name 'x' is not defined

In [32]:
y=df.iloc[:,:-1]

In [33]:
y.shape

(10000, 1)

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

NameError: name 'x' is not defined

In [ ]:
x_train.shape

In [15]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
clf1= GaussianNB()
clf2= MultinomialNB()
clf3= BernoulliNB()

In [16]:
clf1.fit(x_train, y_train)
clf2.fit(x_train, y_train)
clf3.fit(x_train, y_train)

NameError: name 'x_train' is not defined

In [ ]:
y_pred1= clf1.predict(x_test)
y_pred1= clf2.predict(x_test)
y_pred1= clf3.predict(x_test)

In [ ]:
print(x_test.shape)

In [ ]:
y_pred1.shape